bedrock:
  address: 0.0.0.0
  port: 19132
  clone-remote-port: false
  motd1: "GeyserMC"
  motd2: "Another GeyserMC forced host."
  server-name: "Geyser"
remote:
  address: auto
  port: 25565
  auth-type: online
  allow-password-authentication: true
  use-proxy-protocol: false
floodgate-key-file: public-key.pem
command-suggestions: true
passthrough-motd: false
passthrough-protocol-name: false
passthrough-player-counts: false
legacy-ping-passthrough: false
ping-passthrough-interval: 3
max-players: 100
debug-mode: false
general-thread-pool: 32
allow-third-party-capes: true
allow-third-party-ears: false
show-cooldown: true
show-coordinates: true
cache-chunks: true
cache-images: 0
allow-custom-skulls: true
above-bedrock-nether-building: false
force-resource-packs: true
xbox-achievements-enabled: false
metrics:
  enabled: true
  uuid: generateduuid
scoreboard-packet-threshold: 20
enable-proxy-connections: false
mtu: 1400
use-adapters: true
config-version: 4
